# -*- coding: utf-8 -*-
"""
/***************************************************************************
 variablesLiveChanger
                                 A QGIS plugin
 It enables to live change variables context
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-11
        copyright            : (C) 2018 by Thomas Gratier / WebGeoDataVore
        email                : thomas.gratier@webgeodatavore.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load variablesLiveChanger class from file variablesLiveChanger.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .variables_live_changer import variablesLiveChanger
    return variablesLiveChanger(iface)
